### ISSUE TITLE
[FEATURE]有没有Safari版本，且可以将多个浏览器的数据聚合

### ISSUE THREAD

**Issue by einsitang** [sheepzh/timer#106]
非常感谢作者提供了这么好的插件，以前用timing app的时候非常喜欢浏览器的时长记录，但那玩意贼贵，后来没续了，但看到这款插件可以完美替代（chrome），如果可以支持所有市面上的浏览器，并且将已经安装插件的浏览器所收集的数据聚合到数据面板，那就真的perfect了

**Comment by sheepzh** [comment]
目前只上传了 Chrome，Firefox，Edge 的官方商城。更新审核速度 Firefox > Chrome  >>> Edge。

至于其他使用 Chromium 内核的浏览器，360极速和 QQ 等可以在三方平台下载 crx 安装，如果是 Opera 或者 Cent 可以从 Chrome 的商城进行安装。

但是由于 Safari 的插件运行环境跟其他几个主流浏览器完全不同，兼容成本很大，所以目前没有支持，后续可能会考虑，暂时短期内不再计划之中。

至于数据聚合功能，现在的简陋版的解决方案是支持用户从不同浏览器导出各自的 csv / json 数据，然后用其他数据处理工具，比如 excel 甚至 python 进行合并处理。

之前有考虑过将数据传输至云端，但是我没办法保证大家的数据安全。所以更倾向于后续开发一些易用的本地化处理数据的工具。

最后，谢谢您的使用以及反馈！

**Comment by forfuns** [comment]
> 目前只上传了 Chrome，Firefox，Edge 的官方商城。更新审核速度 Firefox > Chrome  >>> Edge。
> 
> 
> 
> 至于其他使用 Chromium 内核的浏览器，360极速和 QQ 等可以在三方平台下载 crx 安装，如果是 Opera 或者 Cent 可以从 Chrome 的商城进行安装。
> 
> 
> 
> 但是由于 Safari 的插件运行环境跟其他几个主流浏览器完全不同，兼容成本很大，所以目前没有支持，后续可能会考虑，暂时短期内不再计划之中。
> 
> 
> 
> 至于数据聚合功能，现在的简陋版的解决方案是支持用户从不同浏览器导出各自的 csv / json 数据，然后用其他数据处理工具，比如 excel 甚至 python 进行合并处理。
> 
> 
> 
> 之前有考虑过将数据传输至云端，但是我没办法保证大家的数据安全。所以更倾向于后续开发一些易用的本地化处理数据的工具。
> 
> 
> 
> 最后，谢谢您的使用以及反馈！

你可以提供云端同步，比如github，dropbox，让用户自行配置存储源

**Comment by sheepzh** [comment]
> 你可以提供云端同步，比如github，dropbox，让用户自行配置存储源

之前有这样的想法，不过会导致整体易用性下降。

如果部分用户如果对这种实现方式能够接受，并且有强需求的话，希望能够反馈一下常用的云端存储平台。我先去调研一下对接方式，然后设计一下对接的公共框架。

**Comment by forfuns** [comment]
> > 你可以提供云端同步，比如github，dropbox，让用户自行配置存储源
> 
> 之前有这样的想法，不过会导致整体易用性下降。
> 
> 如果部分用户如果对这种实现方式能够接受，并且有强需求的话，希望能够反馈一下常用的云端存储平台。我先去调研一下对接方式，然后设计一下对接的公共框架。

恩恩，易用性的问题可以设计为可选项？只有用户需要 `同步` 或者 `整合展示` 的时候才自行配置

感谢作者

**Comment by sheepzh** [comment]
> 恩恩，易用性的问题可以设计为可选项？只有用户需要 `同步` 或者 `整合展示` 的时候才自行配置

数据同步的具体细节新开了 issue 跟踪哈

**Comment by forfuns** [comment]
> > 恩恩，易用性的问题可以设计为可选项？只有用户需要 `同步` 或者 `整合展示` 的时候才自行配置
> 
> 数据同步的具体细节新开了 issue 跟踪哈

我觉得这个功能是不是设计得稍微有点过度了，我的想法是提供`备份`和`云导出`的功能，理论上适配一下云存储的服务就可以，为什么需要考虑后端实现？

**Comment by sheepzh** [comment]
> 我觉得这个功能是不是设计得稍微有点过度了，我的想法是提供`备份`和`云导出`的功能，理论上适配一下云存储的服务就可以，为什么需要考虑后端实现？

不冲突呀，API 定义云备份（增量或者全量）的数据格式，是这次需求需要考虑的功能。
服务器是可选实现，依据前面的 API ，用户可以处理自己的数据整合，属于外部支持模块。具体细节还没想好，先挂一个 task

**Comment by Sciroccogti** [comment]
目前如果多台浏览器设置相同标识的话，是会自动合并还是自动覆盖呢？
