### ISSUE TITLE
[BUG]每日时限限制中的”再看五分钟“界面位置不正确

### ISSUE THREAD

**Issue by Ovler-Young** [sheepzh/timer#119]
## Tell me the enviroment / 请先填写版本信息

Version: 1.1.1
OS: Win11
Browser: Chrome

## Detail / Bug 详情

当设置每日时限限制并开启”再看五分钟“功能后，再看5分钟弹窗界面位置不正确。在Bilibili中体现为弹窗在页面顶端但未能将页面返回顶端，也无法使用鼠标滚轮、方向键、pageup/down 回到页面顶端点击弹窗，从而导致整个网站卡住无法继续操作，刷新网页也无法解决。

**Comment by sheepzh** [comment]
希望提供具体的页面或者截图，我在首页重现时，显示是正确的。
“再看5分钟”也能点击，modal 弹屏会在点击后消失。

![2022-07-04 22-45-23 的屏幕截图](https://user-images.githubusercontent.com/19428473/177178683-3862015a-e3a9-420e-9884-43a5c8933a05.png)


另外，出现模态弹窗时，鼠标滚轮、方向键、pageup/down都会被锁死，属于限制功能设计的一部分。

**Comment by Ovler-Young** [comment]
![image](https://user-images.githubusercontent.com/44089074/177240586-835c83d7-5900-422e-9059-1b56561ae8ee.png)
这个是昨天的截图，今天的时间还没到

**Comment by sheepzh** [comment]
大概知道什么原因了，确实是 bug ，我修复一下。

**Comment by sheepzh** [comment]
css 样式错误，文档流处于中间位置时，到达时限时，模态层会显示异常。

**Comment by sheepzh** [comment]
v1.1.3已修复
