### ISSUE TITLE
[BUG]全屏看视频时统计时间不正确

### ISSUE THREAD

**Issue by Li-Jinyuan** [sheepzh/timer#130]
## Tell me the enviroment / 请先填写版本信息

Version: [Extension version / 1.13
OS: win
Browser: Edge

## Detail / Bug 详情
在bilibili全屏看视频的过程中，统计时间与视频播放时间不一致，最近一次测试为，看了3min视频只统计到了1min左右。该问题出现时间挺久的，大约四五个月前我用该插件就一直有这个问题

**Comment by sheepzh** [comment]
请开启选项中的统计休眠时间

**Comment by sheepzh** [comment]
v1.1.3 之前也有用户反馈偶发出现计时不准确的情况，当时检查是 bug 所致。edge 上 v1.1.3 刚更新不久，您的情况也有可能是 bug 引起的，可以再试试。

**Comment by Li-Jinyuan** [comment]
刚试了下，现在是准确的了，不过为什么没有默认开启这个选项呢，是出于性能考虑吗

**Comment by sheepzh** [comment]
> 刚试了下，现在是准确的了，不过为什么没有默认开启这个选项呢，是出于性能考虑吗

因为我在 pc 上使用浏览器主要是用于工作，经常会直接息屏，短暂离开工位。当时发现回到工位时，如果浏览器没有脱离焦点的话，浏览时间仍旧会增加。后面就开发了这个开关，默认关闭。

因为暂时还没找到一种方法来分辨浏览器进入休眠模式的原因，到底是看视频还是息屏等，所以目前休眠时间默认都不统计。
