### ISSUE TITLE
[FEATURE] 优化 UI 体验

### ISSUE THREAD

**Issue by sheepzh** [sheepzh/timer#138]
> 来自用户邮件反馈

- [x] 弱化运行时长数据展示。
- [x] Popup page 显示平均数。
- [x] 仪表盘使用网站名称显示。
- [x] <del>支持定义合并后网站的名称</del>，与 #140 重复。
- [x] <del>支持缓存表单页的筛选条件，先实现上网习惯页面，其他待定。</del>

**Comment by Okabe-zty** [comment]
感谢大佬！

**Comment by Okabe-zty** [comment]
想知道新版本大概什么时间能做好呀

**Comment by sheepzh** [comment]
> 想知道新版本大概什么时间能做好呀

八月中吧大概

**Comment by Okabe-zty** [comment]
> 
🫡

**Comment by Okabe-zty** [comment]
> > 想知道新版本大概什么时间能做好呀
> 
> 八月中吧大概

那个是新版本还没上线嘛，好像显示平均使用时间和弱化运行时长数据展示的功能还没看到哎
