### ISSUE TITLE
[FEATURE] 希望显示时可以默认合并子域名，并给合并后的域名添加网站名称

### ISSUE THREAD

**Issue by tangjyan** [sheepzh/timer#140]
![image](https://user-images.githubusercontent.com/21167731/187472572-8b62fcc8-d423-4c7c-82c7-807bb716c645.png)
希望可以全局设置默认子域名，并且可以自动抓取子域名网站名称或者自定义网站名称。现在只能给合并前的自定义网站名称，不是很方便。

**Comment by sheepzh** [comment]
功能已实现，将于 v1.2.1 上线，谢谢反馈~
![image](https://user-images.githubusercontent.com/19428473/188599463-cc469305-21a1-4e78-9b80-14a618773509.png)

**Comment by sheepzh** [comment]
至于默认合并的诉求，将设计另外的功能来满足：支持缓存每个表单页的筛选条件，用户访问页面时，默认以上一次的筛选条件进行查询

进度在 #138 中进行跟踪
