### ISSUE TITLE
你好，如果能支持Safari（Safari扩展或油猴子），那就更好了。非常期待！

### ISSUE THREAD

**Issue by ioslxl2015** [sheepzh/timer#148]
你好，如果能支持Safari（Safari扩展或油猴子），那就更好了。非常期待！

**Comment by sheepzh** [comment]
Safari 跟 Chrome/Firefox/Edge 的插件技术不兼容，约等于需要重新写一个，所以暂时不太考虑噢。
油猴脚本似乎不支持常驻后台和大量数据存储，所以很抱歉~

**Comment by ioslxl2015** [comment]
你好，我首先用 xcrun safari-web-extension-converter  --objc /Users/lxl/Downloads/timer进行了转换，
![image](https://user-images.githubusercontent.com/10461646/195486874-1de569a2-e6dd-4728-8a33-b5ded053760a.png)即idle在safrai不可用。

然后，用xcode安装后，安装时提示：银行卡密码问题如图
![image](https://user-images.githubusercontent.com/10461646/195487532-a8d1dc3f-37d1-4d03-9a47-270ff570890f.png)


安装成功后如图：
![image](https://user-images.githubusercontent.com/10461646/195487156-9f59c0da-b83c-4475-b23a-1b6020c8c42c.png)

现在的问题时：
1、该扩展的隐私安全问题逻辑是什么？
2、如何获取统计时间并展示？

非常期待一起解决！

**Comment by sheepzh** [comment]
1. idle 权限在 chrome 里的用途是用来监听电脑的休眠状态变更。
2. safari 指的敏感问题应该是这个插件应用注入了 js，注入 js 在 src/content-script 下，主要实现每日时限拦截。
3. 浏览时间和运行时间由 chrome 的后台 js 每秒轮询统计，代码在src/background/timer/，访问次数由注入的 js 中采集。所有采集数据都存放在 chrome.storage.local 中

**Comment by sheepzh** [comment]
感谢您提供的工具：safari-web-extension-converter，我基于它新建了一个分支 safari_support 用于处理 Safari 的兼容性问题。可能你需要重新 fork 一下仓库才能拉这个分支，因为我之前删除了一些历史文件，主干偏离比较大。

我目前已经处理了 idle 权限的问题，基本功能可用了。不过发现了一些其他的问题，我新开了一个 issue（#152）专门记录与跟进 Safari 的相关 bug。

欢迎加入！
