### ISSUE TITLE
[BUG] 日均时间异常

### ISSUE THREAD

**Issue by Okabe-zty** [sheepzh/timer#149]
## Tell me the enviroment / 请先填写版本信息
v1.2.6 chrome

Version: [Extension version / 扩展版本] 
OS: [操作系统:Mac/Linux/Win]: Mac
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]: Chrome

## Detail / Bug 详情
popup page的每月数据显示的日均使用时间不对，比如今天是10月11号，我的bilibili使用了3小时30分，那么我日均使用时间应该为210/11=19分钟/天，但如图所示他只显示6分30秒/天，感觉是默认使用时间/30天了，但这个日均时间不应该基于当月已经过了多少天来计算嘛。
![WX20221011-171605@2x](https://user-images.githubusercontent.com/110452487/195145627-63e8d2d8-5975-4f59-a28c-febc51fd0423.png)

[Describe the bug / 描述您使用过程中遇到的问题]

**Comment by sheepzh** [comment]
谢谢您的反馈！我看一下~

**Comment by sheepzh** [comment]
已于 v1.2.7 修复
