### ISSUE TITLE
[FEATURE]每次点击都是默认不合并子域名

### ISSUE THREAD

**Issue by everythingCanBeModeled** [sheepzh/timer#161]
在谷歌浏览器中，每次点开都需要手动点击合并子域名，希望可以增加一个设置，默认是否合并子域名，或者固定住选项，在选择过合并子域名后下次打开仍然合并。

![image](https://user-images.githubusercontent.com/75769380/203020380-f044210a-3073-41a2-821d-e8239f73a538.png)

**Comment by sheepzh** [comment]
我觉得在选项中添加一个设置更合适，与右边下拉框保持认知一致。

谢谢反馈~~我会在下一版本加入该功能。

**Comment by sheepzh** [comment]
已于 v1.3.2 发布
