### ISSUE TITLE
[BUG]手动设置的网站名称会被自动抓取的覆盖掉

### ISSUE THREAD

**Issue by everythingCanBeModeled** [sheepzh/timer#162]
在手动设置网站名称后，再次打开网站，仍然会变成自动抓取的名称，希望显示的以手动设置为准。

**Comment by sheepzh** [comment]
按您的描述，这应该是一个 bug，逻辑上应该不会覆盖手动设置的才对。

能不能麻烦您提供以下环境信息，我看能不能复现一下

**Comment by everythingCanBeModeled** [comment]
谷歌浏览器版本号：107.0.5304.63
网站：leetcode.cn

**Comment by sheepzh** [comment]
已经在最新版本复现了，确实是 bug  XDDD

感谢反馈~

**Comment by sheepzh** [comment]
已于 v1.3.2 修复
