### ISSUE TITLE
[BUG] Twitter 时间统计异常

### ISSUE THREAD

**Issue by childeyouyu** [sheepzh/timer#170]
## Tell me the environment 

Version: [Extension version / 扩展版本]：3.1.4
OS: [操作系统:Win11]
Browser: [浏览器名称:Edge/]-[浏览器版本，选填]

## Detail / Bug 详情
推特的时间显示异常
![image](https://user-images.githubusercontent.com/89082776/206263877-d54debd4-18c6-4320-9bc0-a5e8572d66ed.png)

[Describe the bug / 描述您使用过程中遇到的问题]

**Comment by sheepzh** [comment]
我这边复现失败了，麻烦多观察两天？
