### ISSUE TITLE
[HELP] 不清楚如何使用gist同步

### ISSUE THREAD

**Issue by mangost** [sheepzh/timer#173]
首先感谢您开发本扩展，它对我很有帮助。

我在多个地方听说本扩展能使用gist同步，但目前我只找到用gist备份的设置页面

请问开发者是否已经实现了同步功能？如果是，在哪儿设置？

**Comment by sheepzh** [comment]
首先，您需要申请一个包含 gist 权限的 github personal token。然后在设置页面将同步方式选为 gist，将你的 token 填入下方输入框中。点击备份按钮即可将本地数据导入到你的 gist 里。

同时，如果您正确设置了 token，在报表明细页面的右上角会出现一个 cloud 状态按钮，勾选之后，您的查询操作将会同时查询 gist 里的数据。

**Comment by karanotsingyu** [comment]
作者大大你好，可以将这个帖子的内容沉淀到使用手册里（此外，使用手册的入口不好找）

**Comment by karanotsingyu** [comment]
感谢这条帖子的内容，我这位小白解决了使用gist同步的问题。第一次了解和使用token，我先谷歌了一下才搞明白。

可以在帮助文档中附上这两条页面：

* [创建个人访问令牌 - GitHub Docs](https://docs.github.com/zh/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)
* [Personal Access Tokens (Classic)](https://github.com/settings/tokens)

**Comment by karanotsingyu** [comment]
@mangost 楼主你好，参见我的回帖。

在生成token时只需要勾选gist，其它一律不用管。

**Comment by sheepzh** [comment]
> 作者大大你好，可以将这个帖子的内容沉淀到使用手册里（此外，使用手册的入口不好找）

好的，谢谢您的反馈和建议！

**Comment by mangost** [comment]
我找到开启同步的入口了，感谢
