### ISSUE TITLE
[FEATURE] 不清楚如何使用每日时限功能

### ISSUE THREAD

**Issue by jwhsir** [sheepzh/timer#180]
不管怎么设置规则，今日已浏览时间都是0；请问应该怎么设置规则呢，谢谢！
![image](https://user-images.githubusercontent.com/3249691/210779120-30fc6ca4-e7ca-4688-848f-630eeaaeb744.png)

**Comment by sheepzh** [comment]
这样就可以了
![image](https://user-images.githubusercontent.com/19428473/210792457-11bc7755-1d07-4d93-9029-899a451e4442.png)
另外麻烦检查一下你的白名单是不是把 b 站加进去了，所以导致浏览时长没有增长
如果没有拦截特定网站的特定版块的需求的话，不需要使用地址通配符，直接拦截域名就可以了。

**Comment by jwhsir** [comment]
> 这样就可以了 ![image](https://user-images.githubusercontent.com/19428473/210792457-11bc7755-1d07-4d93-9029-899a451e4442.png) 另外麻烦检查一下你的白名单是不是把 b 站加进去了，所以导致浏览时长没有增长 如果没有拦截特定网站的特定版块的需求的话，不需要使用地址通配符，直接拦截域名就可以了。

解决了，谢谢！
