### ISSUE TITLE
[FEATURE]gist 自动同步请求

### ISSUE THREAD

**Issue by cscnk52** [sheepzh/timer#184]
目前同步功能仅限于手动，希望可以增加自动同步选项，避免未备份情况下数据丢失

**Comment by sheepzh** [comment]
感谢反馈～ 功能已经开发完成，将于 v1.4.7 发布
![image](https://user-images.githubusercontent.com/19428473/216573767-bce7c067-15e1-48c9-8b16-ebfc875b4405.png)
同时优化了远程查询功能，支持以tooltip的方式展示每个客户端对应的数据
![image](https://user-images.githubusercontent.com/19428473/216574241-ae437554-b3b5-410a-af00-caf1aefa15f4.png)

**Comment by cscnk52** [comment]
感谢开发，期待AMO中更新
