### ISSUE TITLE
[FEATURE]弹窗饼形图，能否提供“近30天”的选项，个人认为比“本月”更有用。

### ISSUE THREAD

**Issue by bluesword12350** [sheepzh/timer#187]
或者在“报表明细”页面，提供根据筛选数据生成饼形图功能。

**Comment by sheepzh** [comment]
没问题，下个版本（v1.4.8）就安排

**Comment by sheepzh** [comment]
> 麻烦再加一个“昨天”。有时候晚上忘了看，早上想看看昨天的数据。多谢

昨天的数据还是进入报表页查看比较好，因为弹窗页里的筛选是一个常驻选项。换句话说，用户不可能每次点开弹窗页都是为了查看昨天的数据。

当然如果你是想要下载昨天的饼图的话， 后续我考虑丰富一下报表的展示方式。

**Comment by bluesword12350** [comment]
@sheepzh 了解了。

还有一个问题，我是用的edge浏览器似乎升级有点儿问题。
![image](https://user-images.githubusercontent.com/22535595/217808300-f720a95c-a4b7-46df-ade9-7768122a6b3f.png)
我的版本显示是v1.4.5，有个版本升级按钮显示最新版是v1.4.7
我卸载重装也没用，还是v1.4.5
![image](https://user-images.githubusercontent.com/22535595/217808935-06469720-bc13-40b4-a1bf-30a304379b01.png)
我在应用商店里面看到版本说明是v1.4.7不知道是什么情况。

**Comment by sheepzh** [comment]
Edge 经常有这个问题，插件更新过后安装的还是旧版本，之前已经跟他们反馈过了。你如果要更新插件的话，建议在插件管理页右上角手动点击更新按钮，似乎需要开启开发者模式才能看见这个按钮。

**Comment by sheepzh** [comment]
另外， v1.4.7 这个版本还没有实现你的需求，这是上周提交的版本，Edge 审核太慢了今天才上线。不出意外的话， v1.4.8 会在这周末提交。

**Comment by bluesword12350** [comment]
> Edge 经常有这个问题，插件更新过后安装的还是旧版本，之前已经跟他们反馈过了。你如果要更新插件的话，建议在插件管理页右上角手动点击更新按钮，似乎需要开启开发者模式才能看见这个按钮。

我早上起来，什么都没操作，就直接更新为v1.4.7了。不清楚edge更新插件的逻辑。
