### ISSUE TITLE
[BUG]网站标题自动换行

### ISSUE THREAD

**Issue by cscnk52** [sheepzh/timer#189]
## Tell me the environment / 请先填写版本信息

Version: 1.5.0
OS: win
Browser: Firefox-109.0.1

## Detail / Bug 详情

Dashboard遇到标题较长的网站标题不能自动换行，或者也可以考虑省略部分标题

![image](https://user-images.githubusercontent.com/63527850/218356482-7efe9e30-1a36-4dc2-b9f2-4f517b2ed9aa.png)

**Comment by sheepzh** [comment]
收到～

**Comment by sheepzh** [comment]
已于 1.5.2 中更新

**Comment by sheepzh** [comment]
已于 1.5.2 中更新
