### ISSUE TITLE
让侧边导航可以自定义显示的内容

### ISSUE THREAD

**Issue by wordscode** [sheepzh/timer#193]
侧边导航很多功能，但一些使用频率很低，或者根本不会用，希望加个按钮，让用户自定义需要显示的内容

**Comment by sheepzh** [comment]
想问下具体是哪些菜单

**Comment by wordscode** [comment]
额..很多。实际上我喜欢能立即展示数据的东西，比如第一个仪表盘，有图、有表。简单直接
并且很多功能我不需要，比如：报表明细，历史趋势、上网习惯、网站名称管理、子域名合并、白名单管理。
以上这些是我个人不需要的。
报表明细，历史趋势，这两个功能有重合的地方，可以考虑合并了。比如你在报表明细里，点域名直接跳转到历史趋势。
还有白名单管理和每日时限限制，每日时限限制就是限制单个域名了，白名单管理这个功能冗余了。
子域名合并的话，我不清楚这个有什么作用
综上，希望可以加个自定义的功能
