### ISSUE TITLE
[BUG] Sidebar color not consistent on scroll

### ISSUE THREAD

**Issue by Hazem-Gamall** [sheepzh/timer#208]
## Tell me the environment / 请先填写版本信息

Version: 1.7.2
OS: Ubuntu 20.04.6 LTS
Browser: Chrome & Edge

## Detail / Bug 详情

[Describe the bug / 描述您使用过程中遇到的问题]
When i scroll down on the sidebar, the color doesn't stay consistent as shown in the following image:
![img](https://i.imgur.com/stljNCu.png)

**Comment by sheepzh** [comment]
Glad to receive your feedback. I will fix this in next release.

**Comment by sheepzh** [comment]
Fixed and will be published in v1.8.0

![image](https://user-images.githubusercontent.com/19428473/236006661-67612123-0f65-49b9-897c-f4f96c43adc2.png)

**Comment by Hazem-Gamall** [comment]
That's great thank you!
