### ISSUE TITLE
[BUG] Firefox 商城链接异常

### ISSUE THREAD

**Issue by sheepzh** [sheepzh/timer#213]

**Comment by cscnk52** [comment]
https://addons.mozilla.org/zh-CN/firefox/addon/web%E6%99%82%E9%96%93%E7%B5%B1%E8%A8%88/ Firefox商城再次异常，是 Mozilla 那边审核出问题吗
![image](https://github.com/sheepzh/timer/assets/63527850/4da4ed0b-a7f8-46ea-85ae-88c9ce71ea40)
