### ISSUE TITLE
没记录zlib的数据

### ISSUE THREAD

**Issue by kunpeng9** [sheepzh/timer#219]
## Tell me the environment / 请先填写版本信息
最新版本的，时不时更新
Version: [Extension version / 扩展版本]
OS: [操作系统:Mac/Linux/Win]
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]

## Detail / Bug 详情

[Describe the bug / 描述您使用过程中遇到的问题]
怎么好像没记录zlib的数据、https://lib-4qw5th6ag76jgzkjwy72pbr2.must.wf/book/12391081/c27b19 must.wf/book/ 无法搜索到
搜https://lib 也搜不到

**Comment by sheepzh** [comment]
你搜一下 lib
