### ISSUE TITLE
[FEATURE] 支持导出云端数据

### ISSUE THREAD

**Issue by kunpeng9** [sheepzh/timer#220]
## Tell me the environment / 请先填写版本信息

Version: [Extension version / 扩展版本]
最新的
OS: [操作系统:Mac/Linux/Win]
win10
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]
谷歌浏览器版本114.0.5735.134（正式版本）（64位）
## Detail / Bug 详情
今天早上起来发现以前经常使用的一些插件显示损坏了，提示扩展程序可能已损坏，无法开启
只能点击修复，重装了插件，以前的数据统计都没了

本地数据丢失了，怎么恢复，只有上传数据，没有从云端下载数据的设置啊，已经丢了好些次了，大半年的统计记录都没了

[Describe the bug / 描述您使用过程中遇到的问题]
![天若_20230703081849](https://github.com/sheepzh/timer/assets/44609485/8a14731c-7d33-4d98-9d22-951774818e5d)

**Comment by sheepzh** [comment]
目前还没有导出远程数据的功能，稍等一阵，我开发一下

**Comment by sheepzh** [comment]
已开发完毕，将在下一版本中 (v1.9.3) 支持

![image](https://github.com/sheepzh/timer/assets/19428473/e41b3df6-873f-4854-9597-e8b995b991d3)

首先点击下载按钮，选择需要下载的客户端

![image](https://github.com/sheepzh/timer/assets/19428473/3b40137f-3ea7-41e9-9536-5cdd59a81d75)

然后确认数据内容，并选择数据冲突解决方式，点击确认等待下载就 OK 了

![image](https://github.com/sheepzh/timer/assets/19428473/b5c21ef8-efed-4597-809c-7fd041ed91f7)
