### ISSUE TITLE
[FEATURE] Sync with obsidian

### ISSUE THREAD

**Issue by warmbupt** [sheepzh/timer#221]
I think by using [coddingtonbear.github.io/obsidian-local-rest-api](https://coddingtonbear.github.io/obsidian-local-rest-api/), this plugin could sync all the time tracking data to obsidian.

Could anyone also like this feature?

Thanks!

**Comment by warmbupt** [comment]
感谢，同为阿里人……

**Comment by sheepzh** [comment]
> 感谢，同为阿里人……

哈哈哈。好的， 后续版本我加进去，现在在弄其他 feature

**Comment by sheepzh** [comment]
这是个笔记软件吗，我没用过。它支持啥格式呀

**Comment by warmbupt** [comment]
MD格式，我花名马格 咱俩内网认识下？



---Original---
From: ***@***.***&gt;
Date: Mon, Jul 24, 2023 10:27 AM
To: ***@***.***&gt;;
Cc: "Perry ***@***.******@***.***&gt;;
Subject: Re: [sheepzh/timer] [FEATURE] Sync with obsidian (Issue #221)




 
这是个笔记软件吗，我没用过。它支持啥格式呀

**Comment by sheepzh** [comment]
初步开发完成：

**Comment by sheepzh** [comment]
开发完成，将于 v1.9.4 发布

配置界面
![image](https://github.com/sheepzh/timer/assets/19428473/0a96b110-282d-4dbb-a9e7-b03c89109198)

因为 Local REST API 的 HTTPS 接口有跨域限制，所以浏览器的插件相关页面只能使用其 HTTP 服务，需要在插件配置中手动开启

![image](https://github.com/sheepzh/timer/assets/19428473/2d16d9ba-effd-4cd4-b23e-c9f799af3669)

下图导入数据，每个客户端独享一个文件夹，其下文件按日期排列，可预览为表格

![image](https://github.com/sheepzh/timer/assets/19428473/3df3a353-e5f5-4b39-a534-68c2055e9c7b)

**Comment by sheepzh** [comment]
后续优化方向（会在新的 issue 中跟踪

[ ] 用户手册中新增对应条目
[ ] 同时在 md 文件中展示当日的统计指标
