### ISSUE TITLE
Extension unusable in Firefox

### ISSUE THREAD

**Issue by adruzenko03** [sheepzh/timer#224]
## Tell me the environment / 请先填写版本信息

Version: 1.9.1
OS: Windows 11
Browser: Firefox 115.0.2 

## Detail / Bug 详情

For some reason I cannot use this extension on my version of Firefox. I have installed it but when I try to interact with it it looks like this.
![image](https://github.com/sheepzh/timer/assets/17347141/ff0d4e08-d50e-4dd1-bb3c-9383a946c4dd)

I cannot pin the extension, and left clicking does nothing. I cannot interact with the extension in any way except for deleting it.

**Comment by RSHSC** [comment]
have the same problem

**Comment by ikabod** [comment]
seems to be a bug in the extension:
https://discourse.mozilla.org/t/webextensions-how-to-auto-pin-webextension-icon-in-default-toolbar-in-firefox-109/109769/2

**Comment by sheepzh** [comment]
Sorry, guys. I'm checking and seeking solution of this problem

**Comment by sheepzh** [comment]
I adopted a new architecture for measuring time to reduce the memory consumption of this addon. This bug was caused by insufficient testing.

Thank you all soooo much for your feedback !! @adruzenko03 @ikabod @RSHSC 

New version has been released. Please update to v1.9.2

**Comment by sheepzh** [comment]
> seems to be a bug in the extension: https://discourse.mozilla.org/t/webextensions-how-to-auto-pin-webextension-icon-in-default-toolbar-in-firefox-109/109769/2

Thanks! Yeah, there is.

**Comment by ikabod** [comment]
Thank you very much for the quick fix. Now I can use this Add-On.
