### ISSUE TITLE
[BUG] Count data for specific URLs

### ISSUE THREAD

**Issue by ikabod** [sheepzh/timer#225]
## Tell me the environment

Version: 1.9.2
OS: Linux
Browser: Firefox

## Detail / Bug

Options -> Site Management -> +New:

Documentation says:

_Then, fill in the URL to count, Ant expressions is allowed, such as github.com/sheepzh or github.com/sheepzh/timer/**, and the name of this virtual site, and then click Save._

But it is not possible to enter a specific site url in the first input field, since it is no input field, but a select box with different types, where you can only select the first one (__local_files__[MERGED]).

**Comment by sheepzh** [comment]
Hello, @ikabod !The options of this first input form item, exactly the select includes all the domains has been tracked

**Comment by sheepzh** [comment]
Although this is not a bug, I am very sorry that the content on the guide page makes you confused ~

**Comment by ikabod** [comment]
Thank you very much for your detailed answer!

The problem was that I tried to enter a complete url like https://localhost/test.com

It only works if you enter localhost/test.com

Nevertheless, if I visit my test.com site on localhost, the extension will count the time, but in the popup only the name of "localhost" is displayed (in my case it is the php info page which shows up as "php 8.2.8").

I also closed the tab and reopened it, but nothing changed. What can be the problem with this? In the site management the url shows correctly:
localhost/test.com   virtual

**Comment by sheepzh** [comment]
@ikabod  The popup displays the name of this virtual site you added, as default. And you can modify the name of each site in the Site Management.

![image](https://github.com/sheepzh/timer/assets/19428473/70f918f9-7550-415b-8cf5-4df28c3b4cbe)

You can also disable it on the option page, then the domains/URLs of site will be displayed.

![image](https://github.com/sheepzh/timer/assets/19428473/0f71d61e-eb35-4e51-bf45-cf011baecca8)

![image](https://github.com/sheepzh/timer/assets/19428473/ec1ec7ff-9aca-4131-a77b-142ce1aadbc0)

Like this

![image](https://github.com/sheepzh/timer/assets/19428473/cf2eff5c-56ed-4284-8df9-8696cd009674)
