### ISSUE TITLE
[FEATURE] Project Managemant

### ISSUE THREAD

**Issue by ikabod** [sheepzh/timer#226]
Possibly my function request can be achieved with the help of rules, but they are not simple.

I would only be interested in how much time I have spent on a particular project. All other pages do not interest me (at least not while the project is still running).

Therefore a function, which deactivates logging in general, would be useful for me and another function, where I can specify only the web pages, which belong to my project and shall be logged.

E. g. with the help of a new menu item "Projects" in the options manager? After clicking the button "+New" a form opens and asking for the project name and below is a field of the type "textarea" in which I can enter the internet pages to log (one per line). Placeholders (*) should be possible here as well.

**Comment by sheepzh** [comment]
I see. Your core needs is that serveral unrelated sites or urls can be tracked as the same item.

Currently, you can setup virtual sites and rules of site merge to archive it.

I am considering  whether there is a good reason to create a new concept called PROJECT. Or perhaps I should refactor for it based on current functions.
