### ISSUE TITLE
[BUG] Scrollbar shows up in the popup window

### ISSUE THREAD

**Issue by i207M** [sheepzh/timer#237]
## Tell me the environment / 请先填写版本信息

Version: 1.9.5
OS: Windows 10
Browser: Edge 117

## Detail / Bug 详情

![image](https://github.com/sheepzh/timer/assets/32705083/5b5409e2-5f8a-42a1-a4c4-d4468142df9b)

点击扩展图标后弹出的窗口的大小不合适，会有两个方向的滚动条。建议调整使得没有滚动条，或者最多有一个方向的。

**Comment by sheepzh** [comment]
hello，出现滚动条有可能是你修改了界面缩放比例。
为了让用户更清楚的查看数据，弹出页内 document 的宽高设置成了 popup 允许的最大值。当用户开启缩放时，页面内元素会被放大，但是 popup 视窗的最大值并不会变化，所以就会出现页面滚动条。建议先将缩放值还原为 100 %，后续我看下有没有自适配的方案。

**Comment by sheepzh** [comment]
如图，缩放比例小于等于 100% 时则会显示正常

![image](https://github.com/sheepzh/timer/assets/19428473/c9ababf1-d795-4fe3-ab75-d79d1bb9f123)
![image](https://github.com/sheepzh/timer/assets/19428473/c4b98aec-144c-4b4b-ae67-4d097ed3d67b)
