### ISSUE TITLE
[FEATURE] 增加支持从History Trends Unlimited的导出文件导入数据

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [sheepzh/timer#238]
https://chromewebstore.google.com/detail/history-trends-unlimited/pnmchffiealhkdloeffcdnbgdnedheme?hl=zh-CN

**Comment by ParanoiaIsGreat** [comment]
另外还希望一个功能：支持WebDAV备份/恢复数据

**Comment by sheepzh** [comment]
@ParanoiaIsGreat  hello, 我看了下你提供的这个插件（History Trends Unlimited），它应该是读取的浏览器的历史记录，所以只有访问次数数据，没有访问时间。我会新增一个导入历史记录的功能来实现你的需求。

**Comment by sheepzh** [comment]
另外支持 WebDAV 协议这个需求做起来比较复杂，估计会放后面一点

**Comment by sheepzh** [comment]
> @ParanoiaIsGreat hello, 我看了下你提供的这个插件（History Trends Unlimited），它应该是读取的浏览器的历史记录，所以只有访问次数数据，没有访问时间。我会新增一个导入历史记录的功能来实现你的需求。

考虑到兼容旧有的操作流程，实现方式还是导入的 History Trends Unlimited 所导出的数据，而非直接导入浏览器的历史记录。功能已开发完成，将在后续版本 （v1.9.6）中发布

![image](https://github.com/sheepzh/timer/assets/19428473/d97c243a-8a8c-4c02-b708-1846110cf038)

![image](https://github.com/sheepzh/timer/assets/19428473/e2f906dc-4a88-47b1-b51b-4b1549e98e81)

**Comment by ParanoiaIsGreat** [comment]
不好意思，导入该插件产生的.tsv文件，点击下一步时，弹出Invalid file format
![image](https://github.com/sheepzh/timer/assets/10475153/39b2dc02-33d5-402f-a08e-45b5da944d29)

**Comment by sheepzh** [comment]
> 不好意思，导入该插件产生的.tsv文件，点击下一步时，弹出Invalid file format ![image](https://private-user-images.githubusercontent.com/10475153/277158541-39b2dc02-33d5-402f-a08e-45b5da944d29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzUwMTEsIm5iZiI6MTcyOTI3NDcxMSwicGF0aCI6Ii8xMDQ3NTE1My8yNzcxNTg1NDEtMzliMmRjMDItMzNkNS00MDJmLWEwOGUtNDViNWRhOTQ0ZDI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE4MDUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNWRjNWNmNTlkYmIwZWQxODQyMGJmNTc3MGQ5OGQ4NmExZGEwZDU2Njc2NGI5ZjkxZWRlYWQ1M2ViOGE5YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6s05omDm7nHqjbbxawezKfYZ7BO_GnByxxPkHt3xFBo)

很抱歉，由于您的评论没有 reopen 该 issue，所以我之前漏掉了该消息。今天翻看收件箱时才看到您的留言。

您所提到的这个问题有可能是 Windows 注册表异常所导致，前几个版本已经被修复。详见https://github.com/sheepzh/timer/issues/310
