### ISSUE TITLE
希望添加允许某个网站使用的时间段限制

### ISSUE THREAD

**Issue by bigeastldh** [sheepzh/timer#239]
比如，在每天晚8点至9点时才能访问bilibili.com这个网站。这样可以让人在该干什么的时候干什么。
就那我说，我原本计划是在晚上7-8点完成任务，在8-9点娱乐。目前，虽然我有bilibili.com每日时限1小时，但是并没有规定什么时候用。这样我就会在写作业的时间看视频，在娱乐的时间写作业。（主要还是我自制力太差：)）如果有这个功能，我可以设置每天可使用时间段和总共使用时间长度，当两者都满足时才能看视频，这样我就可以更好的自律了 : )

**Comment by sheepzh** [comment]
收到！这个功能已经在迭代中了 
见这个issue #228
