### ISSUE TITLE
[FEATURE] track time for every single page, instead for whole site

### ISSUE THREAD

**Issue by huxh** [sheepzh/timer#242]
and record top 10 pages every day for history, which always means valuable contents.

**Comment by sheepzh** [comment]
Hi, @huxh, thanks for your submission~

Maybe it is not entirely necessary to track any pages by default, I think.

There is little memory  allowed for each extension to store data, while most of the data stored by single page is useless. 

But this extension supports you manually defining one VIRTUAL site with ANT patterns to track any pages you wanna.

Just like the screenshot below

![image](https://github.com/sheepzh/timer/assets/19428473/9d61e8b4-c85e-4c00-951c-42d2f66ba6c8)

And then, URLs hitting this pattern will be tracked into this VIRTUAL site, and you can view its statistics like other normal sites.

![image](https://github.com/sheepzh/timer/assets/19428473/96740d26-6b47-46d0-a84e-a6c60daec8eb)
![image](https://github.com/sheepzh/timer/assets/19428473/82bba91d-8d6a-4323-a9e9-b9747dd51f82)
