### ISSUE TITLE
[FEATURE]建议添加一种针对特定规则永远不会解锁的功能

### ISSUE THREAD

**Issue by bigeastldh** [sheepzh/timer#244]
为什么要添加这个功能：我个人很沉迷b站。我原本设置了一个每天只允许在晚上才能看b站的规则，用的是折磨的验证码解锁。可是后来我经常直接**进设置页面 把解锁方式改成直接解锁 来跳过限制**。我原来的规则就相当于形同虚设了。（还不是我自制力太差）
**新功能描述：**

1. 对于进后台改设置的，我的想法是 添加一种针对特定规则永远不会解锁的功能。比如说我设置了一个限制访问b站的规则，我可以把这个规则设置为“永远不解锁”，当我的浏览时间触发了限制后，这个规则就永远锁住，不提供任何解锁方式，改设置或者关闭“永远不解锁”选项都无法解锁，只能等到第二天规则重置才可以。因为用这个插件限制浏览的人一定是做好了充足的准备 不访问这个网站，所以添加这个功能应该没什么问题，如果担心出事的话可以在开启之前做个声明。

**Comment by sheepzh** [comment]
收到，下个版本安排！

**Comment by sheepzh** [comment]
您所说的在设置页面直接变更解锁方式应该是个产品缺陷，后续再变更时如果检测到触发了具体的规则仍然会要求操作验证
