### ISSUE TITLE
[BUG]在edge浏览器中使用分屏，插件图标会闪烁。

### ISSUE THREAD

**Issue by a285292107s** [sheepzh/timer#246]
## Tell me the environment / 请先填写版本信息

Version: [2.0.2]
OS: [Win]
Browser: [Edge]-[浏览器版本，选填]

## Detail / Bug 详情

edge浏览器中使用分屏功能后，本插件图标上那个蓝色的时间显示会闪烁。
![QQ截图20231216155811](https://github.com/sheepzh/timer/assets/31720768/9639293f-b444-473b-a4f9-23eb0b304f89)

**Comment by sheepzh** [comment]
应该是两屏内的域名不同，导致显示的时间在两个域名之间相互切换。

谢谢您的反馈~~

之前的产品设计没有考虑到分屏的场景，我看看这种 case 怎么交互比较好

**Comment by sheepzh** [comment]
我查阅了扩展开发文档，因为分屏是实验性功能，目前没有相关 API 能够识别标签页是否处于分屏状态。

所以我简单地处理了一下，对于分屏页面只展示左边页的浏览时间。不会根据用户选中的界面进行切换

![image](https://github.com/sheepzh/timer/assets/19428473/f97eb3d2-f1d5-4840-860a-af58a4f19609)

![image](https://github.com/sheepzh/timer/assets/19428473/175f57f7-9e01-4f8d-8d52-2bb01bd9c1a6)

**Comment by sheepzh** [comment]
再次感谢您的反馈，后续官方更新了相关的 API 之后，如果有新的产品变更会再通知您~
