### ISSUE TITLE
[FEATURE]浏览器访问历史明细表

### ISSUE THREAD

**Issue by chixiaome** [sheepzh/timer#248]
之前用的History Trends Unlimited，但原生非中，UI也很差，偶然间发现timer，发现有类似功能但仅限域名而且不会读取历史。
场景是由于谷歌自带历史记录翻起来很麻烦，我想定位到某天访问的具体链接，所以需要时间筛选、图表展示、URL明细及导出功能。
望开发大大支持，祝发财！

**Comment by sheepzh** [comment]
你可以试试这个：https://chromewebstore.google.com/detail/browser-history-+/adjifobelhoemalljgnjdlockheiacmc?hl=en-US&utm_source=ext_sidebar

这个插件重点还是数据统计分析和行为控制，不会叠加太过明细化的数据管理功能
