### ISSUE TITLE
[BUG] Bing 搜索右上角资源加载不全

### ISSUE THREAD

**Issue by cscnk52** [sheepzh/timer#254]
## Tell me the environment / 请先填写版本信息

Version: 2.1.0
OS: Win
Browser: Firefox-121.0

## Detail / Bug 详情

在 bing 上搜索时，在开启插件的情况下会导致部分图片和弹出式对话框无法展开，具体情况如下图所示，使用开发者工具查看猜测是插件阻止了部分资源加载

下图中无蓝色奖牌和开发者工具中无 event 字样的图片是在开启插件的情况下截图的，两者变量仅有插件是否开启

![image](https://github.com/sheepzh/timer/assets/63527850/0e35bbbc-5e9b-4c31-8884-61244fef8f5a)
![image](https://github.com/sheepzh/timer/assets/63527850/509fa164-e73b-45d7-a9ad-bc229b5dab7e)
![image](https://github.com/sheepzh/timer/assets/63527850/f8e36344-5980-4680-80a4-ef47ad885a21)
![image](https://github.com/sheepzh/timer/assets/63527850/850a9b86-9ef1-4c8d-9369-dd6c45964faa)

**Comment by sheepzh** [comment]
这个 bug 虽然很难理解，但是还真是 QWQ

等我仔细查查

**Comment by sheepzh** [comment]
而且似乎只在 Firefox 下能复现， Chrome 和 Edge 都没问题

**Comment by cscnk52** [comment]
确实是这样，有点奇怪，可以考虑降低下优先级，我也尝试修复一下

**Comment by sheepzh** [comment]
> 确实是这样，有点奇怪，可以考虑降低下优先级，我也尝试修复一下

我已经找到原因了，插件注入的 js 和 bing.com 的 js 中的 onload 钩子冲突了。Firefox 不愧是权限最严格的浏览器。。。
