### ISSUE TITLE
[FEATURE] Wondering if could record the time of exactly each URL.

### ISSUE THREAD

**Issue by StLeoX** [sheepzh/timer#261]
Wondering if could record the time of exactly each URL, and then sort and display TopK URL every day.

**Comment by sheepzh** [comment]
With the limited storage provided by Chrome for each extension. It's not supposed to track each URL's time by default.  you can manually create one virtual site with URL or pattern, to track these URLs you want to

**Comment by sheepzh** [comment]
Just like this 
![image](https://github.com/sheepzh/timer/assets/19428473/d40458d3-df80-4369-9c8e-9a2fc821c5f8)
Then, you can the time of it
![image](https://github.com/sheepzh/timer/assets/19428473/a17097d1-0f57-4577-a83f-88a7647eac30)

**Comment by StLeoX** [comment]
This skill partially solved my problem. Helpful!
