### ISSUE TITLE
[BUG] Personal Access Token 测试显示 Invalid type

### ISSUE THREAD

**Issue by YunfangHou** [sheepzh/timer#263]
## Tell me the environment / 请先填写版本信息

Version: v2.1.6
OS: macOS
Browser: Firefox 123.0

## Detail / Bug 详情
使用 GitHub Gist 数据备份，点击「测试」时，显示`Invalid type`。
Personal access token 已选择 Gist 权限，并且该 Token 在 Chrome 端测试则显示 `Valid`，在 Firefox 上则有问题。
<img width="1506" alt="image" src="https://github.com/sheepzh/timer/assets/53991651/a065960d-aa6b-435b-a206-44830a24f050">

**Comment by sheepzh** [comment]
感谢反馈， v2.1.7 已修复

**Comment by YunfangHou** [comment]
> 感谢反馈， v2.1.7 已修复

已更新 v2.1.7，可正常使用👍
