### ISSUE TITLE
[FEATURE] 白名单支持 URL 通配或更细粒度

### ISSUE THREAD

**Issue by byfy** [sheepzh/timer#274]
首先感谢大佬，这个插件很有用，反馈个需求：希望白名单功能能支持 URL 通配符或更细粒度，比如在限制了黑名单是 www.bilibili.com 的情况下，设置白名单是 www.bilibili.com/video/*。
因为有时候希望能阻止掉首页信息流，但是从搜索引擎过来的还是希望可以加白。之前使用的 WasteNoTime 支持这种能力，所以迁移过来就这点不太适应，希望能考虑下，感谢~

**Comment by sheepzh** [comment]
收到

**Comment by sheepzh** [comment]
该功能预计将于 v2.2.9 中上线

**Comment by byfy** [comment]
收到，非常感谢，太速度了！
