### ISSUE TITLE
插件在页面上计时开始后，能不能关闭 闪烁？

### ISSUE THREAD

**Issue by findink** [sheepzh/timer#276]
这好像是最近新增的效果，不知道为什么会上线这个效果。闪得我头痛，又找不到关闭的地方。😢

**Comment by sheepzh** [comment]
这有可能是bug，麻烦给一下环境信息和复现步骤

**Comment by findink** [comment]
解决了，游览器更新安装后就没问题了，感谢。

PS: 确实是游览器的bug, 不过应该是主动bug,你不更新就给你整一堆问题。

环境： Microsoft Edge
版本 123.0.2420.81 (正式版本) (arm64)
