### ISSUE TITLE
[FEATURE]时间限制的网站能否支持通配符

### ISSUE THREAD

**Issue by darkriverdell** [sheepzh/timer#277]
我不太确定，但根据我的尝试，该插件的时间限制网站似乎不支持通配符。

一方面，像微博这样的网站域名有好多个weibo.com, weibo.cn, m.weibo.cn等等，我限制的时候一个一个输入很麻烦。

另外其他的一些网站限制插件基本都允许通配符，用户迁移过来也比较容易。

**Comment by sheepzh** [comment]
@darkriverdell 目前已经支持

你可以这样输入
![Screenshot from 2024-06-28 22-50-06](https://github.com/sheepzh/timer/assets/19428473/ecad4cf9-079a-4601-81b5-b50ba1c4fbfb)

m.weibo.cn 和 weibo.com 和 xxxx.weibo.xxx 都会被限制
