### ISSUE TITLE
[FEATURE]这么优秀的插件，使用量相对太少了！

### ISSUE THREAD

**Issue by EntropyProduction** [sheepzh/timer#278]
可能对作者来说并不太上心，可我还是希望能多多推广，让更多的人用上这么好的软件作品！大言不惭的在此提出几点建议：

1. 此类插件用户最敏感的是隐私和安全性，作者虽然在官网的隐私政策里也有提及，但我觉得值得放在首页等显著位置。
2. 作者应该在首页多放几张精美的截图，对用户的吸引力会大大提高！此类作品虽也有竞品，但精美的界面和丰富的功能无疑是本软件的大优势！
3. 希望能增加更多安全的同步方式，方便多平台数据同步。

**Comment by sheepzh** [comment]
衷心谢谢你的建议！！
