### ISSUE TITLE
[FEATURE]提供更改 badge 颜色的选项

### ISSUE THREAD

**Issue by YunfangHou** [sheepzh/timer#279]
就是`扩展图标`上`当前网站的今日浏览时长`的 badge，是否可以提供更改颜色的选项？目前的红色有点扎眼了。

应该是调用 `browserAction.setBadgeBackgroundColor()` 吧，但是别的技术栈我不太会，所以只能提 issue 没法提 PR 了😬

**Comment by sheepzh** [comment]
不过，我想确认以下你的浏览器环境。背景色应该是蓝色诶，为啥你的是红色

**Comment by YunfangHou** [comment]
操作系统：macOS 14.4.1

浏览器：
- Google Chrome 120.0.6099.216 (Official Build) (x86_64)
- Firefox 125.0.3 (64-bit)

Google Chrome 上，深色模式下标签为黑色，浅色模式下标签为白色。
Firefox 上，深色模式、浅色模式下标签均为红色。我平时主要用 Firefox，所以之前说是红色。


<img width="1280" alt="SCR-20240505-pelh" src="https://github.com/sheepzh/timer/assets/53991651/59d7d1c2-9b7e-4340-9b4f-4cbc069760dd">
<img width="1280" alt="SCR-20240505-perp" src="https://github.com/sheepzh/timer/assets/53991651/fc7e6508-ec50-40b2-a3de-6a23962e549d">
<img width="1280" alt="SCR-20240505-peob" src="https://github.com/sheepzh/timer/assets/53991651/38fd08f0-fc2e-4816-94fa-f5d6d363a42d">
<img width="1280" alt="SCR-20240505-pepr" src="https://github.com/sheepzh/timer/assets/53991651/dd7ec615-be87-4ac0-a1c8-400a3158e3ac">

**Comment by sheepzh** [comment]
实验了一下，这个颜色默认好像是跟随浏览器的主题色的 qwq

功能已经开发完了，预计一两天内上架新版本（v2.3.0
