### ISSUE TITLE
[BUG]限制规则在非生效时间区间生效

### ISSUE THREAD

**Issue by byfy** [sheepzh/timer#280]
## Tell me the environment / 请先填写版本信息

Version: [Extension version / 扩展版本] 2.2.9
OS: [操作系统:Mac/Linux/Win] Windows 11 
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填] Edge

## Detail / Bug 详情

[Describe the bug / 描述您使用过程中遇到的问题]
限制规则在非生效时间区间生效了。怀疑
1. 当天只要某个网站被某个规则限制，就算过了限制时间，也会继续生效
2. 插件使用的时间，比正常时间快一个小时，比如当前是23:57 UTC+8, 却命中了00:40~06:00 的规则

<img width="1907" alt="image" src="https://github.com/sheepzh/timer/assets/12696524/f4809476-3f0c-45f1-b1db-16bc62dd886d">

**Comment by sheepzh** [comment]
根据截图，目前生效的规则应该是今日浏览时间限制而不是受限时间段

**Comment by byfy** [comment]
> 根据截图，目前生效的规则应该是今日浏览时间限制而不是受限时间段

确实，看了下手册，受限时间和每日限制浏览时间是 OR 的关系，不是 AND。这个和之前用的插件不太一样，建议可以考虑增加规则生效时间。
