### ISSUE TITLE
[BUG] 刷新页面后有几率让时间限制失效

### ISSUE THREAD

**Issue by yjqOUO** [sheepzh/timer#284]
## Tell me the environment / 请先填写版本信息
2.3.1
Version: [Extension version / 扩展版本]
OS: [操作系统:Mac/Linux/Win] win11
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]
chrome
## Detail / Bug 详情
刷新页面后有几率让时间限制失效
[Describe the bug / 描述您使用过程中遇到的问题]
我在看b站视频时发现，当超过当日使用时限后，刷新页面有几率导致当日限制失效。
大概刷新3-4次会有一次弹出限制窗口。

**Comment by yjqOUO** [comment]
直接输入bilibili.com不会弹出限制窗口，但刷新后或点击视频时会弹出限制窗口，限制窗口后视频似乎仍在播放。
这个bug不太影响使用。

**Comment by sheepzh** [comment]
能否贴一下您的规则配置，和具体的复现页面。有可能是页面 URL 重定向导致的，我排查一下

**Comment by yjqOUO** [comment]
补充：访问NGA.178.COM时也会出现类似问题。
![1715651200463](https://github.com/sheepzh/timer/assets/169360519/7e9a4906-1912-44a1-97a2-4ce9d72491fd)

**Comment by sheepzh** [comment]
> NGA.178.COM

按样子应该是滚动条没失效成功，以致用户可以滚动界面，把遮罩页滚出视野区了
