### ISSUE TITLE
[BUG]在实际未浏览的界面停止仍计算时长

### ISSUE THREAD

**Issue by IncWu** [sheepzh/timer#288]
## Tell me the environment / 请先填写版本信息

Version: 2.3.2
OS: Windows 11
Browser: Edge

## Detail / Bug 详情

在我的浏览器停止在页面上时，实际上并未浏览页面（滚轮，按键，点击等操作），插件也会记录时长。
以B站首页为例，当我只是浏览器停留在首页界面上，就持续记录了停留时间，这在反过来查看数据时造成困扰：
![bug1](https://github.com/sheepzh/timer/assets/48884973/9902732d-2cac-444b-8189-fe92d88387a4)

另外：本人在公司的工作电脑上也安装了插件，但是不会出现这种情况，拓展只会在浏览界面发生相应动作时记录时间

**Comment by sheepzh** [comment]
正常情况下，这种时间会被记录的。但是在休眠状态下插件应该不会工作，如果你的工作电脑开启了自动休眠，可能就不会纪录时间。因为插件不太好处理用户操作，所以没有添加自动停止计时这种功能

**Comment by IncWu** [comment]
> 正常情况下，这种时间会被记录的。但是在休眠状态下插件应该不会工作，如果你的工作电脑开启了自动休眠，可能就不会纪录时间。因为插件不太好处理用户操作，所以没有添加自动停止计时这种功能

在我的工作电脑上，以浏览V2EX为例：当打开网页后，会记录几秒时间后停止记录，当我滚轮下滑浏览时，会继续记录时间，停止下滑后，也会记录几秒后停止记录。
但是在我自己的电脑环境下，只要当前聚焦在页面上，就会持续记录时间。
关于自动休眠，我查看了个人电脑的相关设置，如果指的是标签页休眠功能，我的设置是打开的
![休眠状态](https://github.com/sheepzh/timer/assets/48884973/3d8a2a77-06b6-4d79-b506-2cbfc35e1ceb)

**Comment by sheepzh** [comment]
感觉像您的工作电脑有 bug 呢  XD

**Comment by IncWu** [comment]
> 感觉像您的工作电脑有 bug 呢 XD
> 
> 麻烦多描述一点你工作电脑的环境信息

十分抱歉！我工作电脑上的使用习惯使我误判了ㄒoㄒ
在工作电脑上，我日常的使用习惯是IM与浏览器的窗口轮流聚焦，这使得当我聚焦在IM窗口时（我仍以为我聚焦在浏览器），我看到了计时停止，造成了误判；我另一个习惯是在离开工位时就会WIN+L锁屏，同样会使得计时停止。
以上两个习惯与我在家里的使用环境不一致，让我觉得拓展出了问题，应该是非问题的。
再次抱歉！
