### ISSUE TITLE
[BUG]  锁定页面可以滑动跳过

### ISSUE THREAD

**Issue by cscnk52** [sheepzh/timer#289]
## Tell me the environment / 请先填写版本信息

Version: 2.3.2
OS: Win
Browser: Firefox 126.0.1

## Detail / Bug 详情

在页面被锁定后可以通过滚轮继续浏览剩余的内容
![动画](https://github.com/sheepzh/timer/assets/63527850/82e72e8e-b638-4737-a99e-6c6a9ee3a4f8)

**Comment by sheepzh** [comment]
麻烦给一下网站，有可能是 css 冲突

**Comment by cscnk52** [comment]
已经找到问题了，是我使用的 `uBlock Origin` 中订阅了 `uBlock filters – Annoyances`, 而这个项目中的这个 uBlockOrigin/uAssets#15430 issue 为了保证 Twitter 注册窗口弹出窗口被拦截后可以继续滚动，添加了 `twitter.com##html:style(overflow:auto!important)` (当然，现在是 x.com) 这个规则，而插件的 `limit` 模块的阻止滚动也是通过设置这个滚动条的值实现，两者导致了冲突，且由于前者为其加了 `important` 属性，修改不生效。

其实本身想直接提 PR 的，改了半天也没有想到一个合适的解决办法。由于我 js 能力有限，于是就暂时说明下问题所在，抱歉。

**Comment by sheepzh** [comment]
既然是这样的话！那我们也加上 !important

**Comment by cscnk52** [comment]
是的，我昨天也想到这个办法了，但是好像看起来并不生效，最新的源码构建的开发版也并没有解决问题，在 Chrome DevTools 中查看确实样式被注入了，但是效果还是可以滚动，但理应不应该滚动
![image](https://github.com/sheepzh/timer/assets/63527850/35e7c78d-03c2-404a-a01d-71261f321860)
![动画](https://github.com/sheepzh/timer/assets/63527850/b8e2c050-77b7-4342-9876-34d9f33a35d9)
