### ISSUE TITLE
Time not tracked for local files

### ISSUE THREAD

**Issue by VitorX** [sheepzh/timer#290]
## Tell me the environment / 请先填写版本信息
Version: [Extension version / 扩展版本]
OS: [操作系统:Mac/Linux/Win]
Win
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]
Edge
## Detail / Bug 详情
[Describe the bug / 描述您使用过程中遇到的问题]
Dashboard doesn't show the time for local pdf file and there is no record in the table

**Comment by sheepzh** [comment]
Please make sure the following option is enabled. The latest versions of browsers have this option disabled by default.

For Chrome
![image](https://github.com/sheepzh/timer/assets/19428473/d72daddd-d531-43ab-9531-0aa7437be8d6)

For Edge
![image](https://github.com/sheepzh/timer/assets/19428473/8dfe6f06-e1c1-4b9c-b1c7-25aa9516b8fa)

**Comment by VitorX** [comment]
Thanks for the quick response, enable this options fix this issue
