### ISSUE TITLE
[FEATURE] Time tracking based on URL parameters

### ISSUE THREAD

**Issue by limbera** [sheepzh/timer#291]
Is it possible to have time tracking not merge urls on the same website?

i want to use your product to track the number of time spent on each of these websites:

www.mysite.com/profile/100
www.mysite.com/profile/101
www.mysite.com/profile/102
www.mysite.com/profile/103

so that i can say:

i spent X minutes on profile 100
i spent Y minute on profile 101
i spent Z minute on profile 102

etc..

is this possible?

**Comment by sheepzh** [comment]
@limbera yes, this extension supports your request.

please see these issues #191 #242

**Comment by limbera** [comment]
thank you for getting back to me sheepzh. 

however, i don't fully understand how to implement this.

here's what i am trying to do:

1. go to site management 
2. click on green new button
3. try to enter site url with a wildcard in it (e.g. in image)

but i can't figure it out.

<img width="583" alt="image" src="https://github.com/sheepzh/timer/assets/2503457/2606e4ca-3149-43e5-ba1b-8cb34e49644f">

**Comment by sheepzh** [comment]
@limbera Hello, you could enter `securestaging.gethealthie.com/users/*` without the protocol prefix, and then you can select the first option like following
![image](https://github.com/sheepzh/timer/assets/19428473/707db468-be7b-4765-a9cc-988e288052f3)

Also if you want to record the time of specified user, you can enter like this `securestaging.gethealthie.com/users/[userId]`

**Comment by limbera** [comment]
i don't totally understand how this would work. here is what i have setup:

<img width="1728" alt="image" src="https://github.com/sheepzh/timer/assets/2503457/929627a4-8189-4ebc-aa41-9886685203ea">


and then when i navigate to 

https://securestaging.gethealthie.com/users/471056
https://securestaging.gethealthie.com/users/324124
https://securestaging.gethealthie.com/users/745452

i still see only a single time bucket for https://securestaging.gethealthie.com

when what i am hoping to achieve is a time allocated to 471056, 324124 and 745452

does that make sense?

**Comment by sheepzh** [comment]
@limbera Sorry, I miss something.

The [userId] should be replaced by specific value.

In you cases, it's should be 471056, 324124 and 745452. So you need setup 3 rules with different URLs.

* securestaging.gethealthie.com/users/471056
* securestaging.gethealthie.com/users/324124
* securestaging.gethealthie.com/users/745452

**Comment by limbera** [comment]
i don't want to have to list each url one by one, there are thousands of values for userId. is this possible?

**Comment by sheepzh** [comment]
For that, this extension can only track the total time spent on all the users' pages, and not the time spend on each user's 

You can setup it like this `securestaging.gethealthie.com/users/*`
