### ISSUE TITLE
[FEATURE]开发者你好，能问一下在哪里下载到旧版的crx文件吗

### ISSUE THREAD

**Issue by Tacenda5618** [sheepzh/timer#292]
出于一些特殊原因，我的浏览器版本停留在(Chromium 86.0.4240.198)，搜索了网上的资源，都找不到插件的历史版本crx文件，特此求助，很抱歉带来麻烦。

**Comment by sheepzh** [comment]
Chromium v88 之前应该是 mv2 架构，目前 Firefox 下的所有版本都是使用的 mv2，你可以在 Firefox 商城下载对应安装包，文件后缀名是 xpi，本质其实是个压缩包，解压后倒入浏览器就行
