### ISSUE TITLE
[BUG]再看五分钟时的今日浏览时长统计存在问题

### ISSUE THREAD

**Issue by Ovler-Young** [sheepzh/timer#295]
## Tell me the environment / 请先填写版本信息

Version: v2.3.5
OS: Win
Browser: Chrome-126.0.6478.116

## Detail / Bug 详情

在设置了今日浏览时长的情况下，超时提醒时的`今日浏览时长`与实际不符。

如下方例子，实际使用时长为1h35min，但插件显示为1h0min，极接近设置的每日限制时长。

![image](https://github.com/sheepzh/timer/assets/44089074/a3f47275-133f-4245-9842-9e9d0c2a80a7)

**Comment by sheepzh** [comment]
hello，想了解下有没有点击过再看五分钟，点击了之后今日累计时长会减五分钟。

**Comment by Ovler-Young** [comment]
是有点击过的，这个点了之后减5分钟好像不是很能理解意义所在了……

**Comment by sheepzh** [comment]
@Ovler-Young 抱歉，这里应该是概念没表达清楚，其实指的是今天已经累计到规则里的时间，不是观看网站的时长，因为一条规则可以包含很多条 URL，所有 URL 的累计和会加在一起，跟当前域名的当日时长不是同一个概念。

**Comment by Ovler-Young** [comment]
理解了，但感觉这个再看5分钟也不应该把已经计入规则的时间再抹去

**Comment by sheepzh** [comment]
明白你的意思了，后续优化下这里，记录更详尽的数据，把今日点击再看五分钟的次数都记录下来，然后综合计算可以观看的时长

**Comment by zjx-kimi** [comment]
我根本没有这个按钮！！！
mac + google

**Comment by sheepzh** [comment]
> 我根本没有这个按钮！！！ mac + google

@zjx-kimi 您好，请查看下您是否在规则上开启这个功能，正常开启后的拦截图是这样的

![image](https://github.com/user-attachments/assets/8c97b722-159c-4b5d-9701-cd1124ba72c9)

如果方便的话也希望能够提供下拦截界面截图，以及规则配置截图
