### ISSUE TITLE
[FEATURE]能否出一个读取在线浏览记录的功能？

### ISSUE THREAD

**Issue by billowssun** [sheepzh/timer#297]
软件的数据汇总统计功能非常好用~
作为一个经常在不同电脑上使用网页浏览器的人，我需要一个能读取浏览记录

**Comment by sheepzh** [comment]
目前是可以支持的哦，不过需要你在多个浏览器里都配置一下数据备份策略。扩展不提供官方的数据备份服务，目前只支持使用 Github Gist 或者 Obsidian 进行备份。比如下图我配置了 Github 备份

![截图 2024-07-25 00-43-07](https://github.com/user-attachments/assets/84305f61-9544-4b2c-a799-38cb1619a750)

配置正确的话，在数据明细页面的右上角会出现远程数据的开关按钮，点击即可查询其他浏览器备份在三方服务里的数据。

![image](https://github.com/user-attachments/assets/319b28a3-53ed-45a6-b3e2-ae52e5f5eae5)

把鼠标置于各个数据项上就能看到各个浏览器内的数据占比

![image](https://github.com/user-attachments/assets/7c26bb28-f102-429e-b466-63d7bb093d96)

至于其他图表，目前暂不支持展示多端数据
