### ISSUE TITLE
[BUG]仪表盘只显示半截

### ISSUE THREAD

**Issue by DentistCode** [sheepzh/timer#298]
## Tell me the environment / 请先填写版本信息

Version: v2.3.6
OS: Win
Browser: edge 126.0.2592.87 (正式版本) (64 位)

## Detail / Bug 详情

如图，github只显示半截（以前在这个位置的网站都显示半截，不仅仅是github）

![Snipaste_2024-07-26_08-39-39](https://github.com/user-attachments/assets/abc9f88b-12b2-431a-b957-bfb4e63920c7)

**Comment by DentistCode** [comment]
- 已经重装过插件，但无果
- 是长期以来一直这么显示

**Comment by sheepzh** [comment]
@DentistCode 很高兴收到您的反馈

这里用的蜡烛图不是柱形图，红色部分代表 wow 的增量，绿色代表减量，所以不是 bug。

不过它导致你产生了疑惑，我觉得这里的产品表述应该没表达清楚。后续可能会替换掉这个图表，或者改成其他展示形式
