### ISSUE TITLE
休眠状态仍计入时间

### ISSUE THREAD

**Issue by YiHui-Liu** [sheepzh/timer#3]
浏览器保持后台运行，电脑休眠，休眠的时间会被计入浏览时长

**Comment by sheepzh** [comment]
> 浏览器保持后台运行，电脑休眠，休眠的时间会被计入浏览时长

请问是哪款浏览器，什么操作系统呢？

**Comment by YiHui-Liu** [comment]
> > 浏览器保持后台运行，电脑休眠，休眠的时间会被计入浏览时长
> 
> 请问是哪款浏览器，什么操作系统呢？

chrome 87.0.4280.88
网费很贵 - 上网时间统计 v0.0.9
Windows10
联想小新13pro

**Comment by sheepzh** [comment]
好的我查看下原因。当前逻辑是浏览器的标签页失焦后会自动停止计时，所以还有一点需要您的确认，方便更好的查找问题：

+ 您是在浏览器处于桌面顶层的时候进行电脑休眠的吗？

**Comment by YiHui-Liu** [comment]
> 好的我查看下原因。当前逻辑是浏览器的标签页失焦后会自动停止计时，所以还有一点需要您的确认，方便更好的查找问题：
> 
> * 您是在浏览器处于桌面顶层的时候进行电脑休眠的吗？

显示桌面（win10右下角的按钮）后休眠的（合盖，电源设置已设定合盖休眠）

**Comment by sheepzh** [comment]
修复内容将随版本 v0.1.0 发布
