### ISSUE TITLE
[FEATURE] 可否添加 blacklist ？禁止某网站访问，或者限制网站访问时间

### ISSUE THREAD

**Issue by john916zhang** [sheepzh/timer#308]

**Comment by john916zhang** [comment]
time limit 可以禁止网站访问。

可否把网站分类，然后根据类型设置 time limit 规则？ 比如 facebook, twitter等网站归为一类，然后给这个类型设置 time limit 规则。

**Comment by sheepzh** [comment]
@john916zhang 右键图标，有一个【全部功能/All Functions】的菜单，点击进去之后就能看到时间限制相关的功能。
