### ISSUE TITLE
[BUG] 数据迁移时，tsv数据无法导入

### ISSUE THREAD

**Issue by Vicwxy9** [sheepzh/timer#310]
## Tell me the environment / 请先填写版本信息

Version: v2.4.2
OS: Win
Browser: Chrome

## Detail / Bug 详情

![image](https://github.com/user-attachments/assets/ee9a8de1-28dc-4507-9f7b-de9f4526332e)

数据迁移时，无法导入tsv数据

**Comment by Vicwxy9** [comment]
![image](https://github.com/user-attachments/assets/75d14b44-d1f1-4451-b2a1-eddd27969359)

**Comment by Vicwxy9** [comment]
![image](https://github.com/user-attachments/assets/074323f1-f249-4510-ae8b-a49ed7feaa72)
似乎需要另外一种处理方式？

**Comment by sheepzh** [comment]
@Vicwxy9 感觉是你这个文件有问题，file.type 是空字符串。搜索了下，部分 Win10 的注册表如果被篡改了话，文件头里的 type 会为空。

参考：https://stackoverflow.com/questions/51724649/mime-type-of-file-returning-empty-in-javascript-on-some-machines。

扩展本身 tsv 是支持解析的，参考源码：https://github.com/sheepzh/timer/blob/main/src/app/components/DataManage/Migration/ImportOtherButton/processor.ts。正常情况下 .tsx 文件的文件头类型应该是 text/tab-separated-values。

你这种 case 的话，麻烦先手动修复一下注册表，后续我看看能不能兼容一下 Windows 系统的这种场景。

**Comment by Vicwxy9** [comment]
![image](https://github.com/user-attachments/assets/ab260ed6-15c2-44bb-b811-865da57923b9)
修改注册表的后，确实成功了，感谢！
