### ISSUE TITLE
[FEATURE]添加webdav远程同步

### ISSUE THREAD

**Issue by 1677883418** [sheepzh/timer#314]
插件很棒!!但是有个困扰的问题就是远程同步太过于麻烦,我尝试了一下obsidian同步,发现很难同步成功,一直not found,只有一次连接成功,但是使用官方api在终端下通过curl请求api可以成功,是否可以添加webdav远程同步功能

![图片](https://github.com/user-attachments/assets/fac45252-5d61-4659-99dd-48d817e574e8)

还有个问题,唯一成功的一次,点击备份数据后我发现一直显示doing backup,但是看obsidian数据已经不写入了,这个应该算一个bug?

**Comment by 1677883418** [comment]
我把项目拉下来看了一下,发现不是项目的问题
obsidian里一个目录是空目录,通过API请求就不会显示这个文件夹,这就是为什么刚刚成功了一次

**Comment by 1677883418** [comment]
当页面请求备份的时候,会出现上面的请求

![图片](https://github.com/user-attachments/assets/43c5a147-f1bb-4c11-a86b-3dc2840acf01)

实际上这边已经写入完成了,但是网页会一直卡在那个 doing backup

![图片](https://github.com/user-attachments/assets/d62ae2cc-37b0-47e8-aaf1-15af809d6f1c)


下面是控制台报错信息:

![图片](https://github.com/user-attachments/assets/2505253b-8bbb-463b-96e7-8a81251270fa)

**Comment by sheepzh** [comment]
靠！好像真是一个 bug  = =

谢谢你的反馈，我修复一下。

至于你提到的 webdav 支持，已经有另外一个 issue #257 在跟踪，也有同学提了 PR #286 

因为我没有使用过 webdav，所以如果你有推荐的这类服务的话也可以麻烦告知，后面考虑我直接接入

**Comment by sheepzh** [comment]
@1677883418 紧急修复了这个 bug，将于 v2.4.4 中发布，该版本已经提交商城审核，再次感谢你的反馈！

至于你提到的一直提示 Not Found 的那个问题，是因为你的 Obsidian 仓库名和插件内置的仓库名(vault，之前 obsidian 的默认仓库名) 不一致，所以找不到文件夹，这应该算一个产品设计缺陷。

我将仓库名改为用户可配置了，并且优化了错误提示。

![image](https://github.com/user-attachments/assets/285433e4-e8d9-47b1-8e15-b72dfec4c1dd)

**Comment by 1677883418** [comment]
> 靠！好像真是一个 bug = =
> 
> 谢谢你的反馈，我修复一下。
> 
> 至于你提到的 webdav 支持，已经有另外一个 issue #257 在跟踪，也有同学提了 PR #286
> 
> 因为我没有使用过 webdav，所以如果你有推荐的这类服务的话也可以麻烦告知，后面考虑我直接接入

作者真是劳模😳，感谢作者的快速响应🥳🥳!!!
然后的话，webdav是一种可以调用远程文件的协议(类似于samba共享)，可以理解为云盘之类的。

比较出名的服务有坚果云(闭源商业)，还有就是支持s3协议的一些云存储服务，比如说亚马逊云的s3，阿里云的oss，还有腾讯云的我忘记叫什么了，阿里云的云存储9块钱40g可以用一年

理论上来说有链接，id和密钥就可以进行云盘的管理，接口都是类似的(坚果云和其他云存储都是)

作者如果使用obsidian的话，可以看一个插件叫 remotely sync(应该是这个，我明天确认一下) 他就是利用了兼容s3协议的云存储在多平台进行增量同步

目前来看使用webdav的备份一般有两种方式，备份和同步

共同点就是需要填写链接，id和密钥的三元组，最多再加上保存路径

备份一般的逻辑是用时间戳做文件名，打完zip包上传到云存储，留3-5份，然后另一台机器自动解压后恢复数据，本地合并数据(这种应该算全量同步？)

同步的话，可能是直接在云存储上保存结构化数据，然后上传的时候和本地文件用md5比较，上传变动和没有的文件(我看了下引用的关于webdav的issue，感觉冲突的应该不会多？因为大概率不会同时看两个浏览器吧😳但是合并数据可能会涉及很多问题)

大概就是这些，如果作者需要webdav的账号进行测试的话我可以提供，再次感谢作者的无私奉献！

**Comment by sheepzh** [comment]
@1677883418 好嘟，谢谢你！

我晚上回家买一个阿里云盘试试，公司的电脑不能登私人账号

**Comment by sheepzh** [comment]
将在 v2.4.5 中支持

**Comment by 1677883418** [comment]
> 将在 v2.4.5 中支持

感谢作者!

**Comment by sheepzh** [comment]
@1677883418 如果有 webdav 使用上的问题或者 bug 反馈的话，欢迎 reopen 这个 issue
