### ISSUE TITLE
[BUG] 数据备份 gist 和 webdev 都无法使用

### ISSUE THREAD

**Issue by Ocyss** [sheepzh/timer#324]
## Tell me the environment

Version: v2.5.0
OS: MacOS 和 Windows 都报错
Browser: Microsoft Edge - 130.0.2849.56 (正式版本) (arm64)

### WebDav 上传报错提示 `Failed to write file or create directory: 204`
使用的坚果云
```
Error to sync data Error: Failed to write file or create directory: 204
    at y (api.js:2:66788)
    at api.js:2:66580
    at p (api.js:2:57869)
    at Generator.<anonymous> (api.js:2:59211)
    at Generator.next (api.js:2:58298)
    at i (api.js:2:63772)
    at c (api.js:2:63975)
(匿名) @ app.js:2
...
```

### Gist 报错

报错了, 但gist也会成功创建, 多点几次上传就会创建多个gist

报错是一个 json, 不知道有没有敏感数据就先摘要了个 description
` Used for timer to save stat data. Don't change this description :)`

```
Error to sync data Error:   Used for timer to save stat data. Don't change this description :)
    at api.js:2:35651
    at p (api.js:2:27881)
    at Generator.<anonymous> (api.js:2:29223)
    at Generator.next (api.js:2:28310)
    at i (api.js:2:33784)
    at c (api.js:2:33987)
```

**Comment by sheepzh** [comment]
感谢反馈

Gist 报错是因为 Github API 的返回码变了，已修复

坚果云感觉是路径配置错误，能否给一下坚果云的配置和插件的配置

**Comment by Ocyss** [comment]
> 感谢反馈
> 
> Gist 报错是因为 Github API 的返回码变了，已修复，下版本发布
> 
> 坚果云感觉是路径配置错误，能否给一下坚果云的配置和插件的配置

服务器地址: https://dav.jianguoyun.com/dav
文件夹路径: /wfhg-cc

之前是有手动同步成功过的, 但后面不知道怎么就一直失败了

**Comment by sheepzh** [comment]
没用过坚果云，不过一般 webdav 的协议里，endpoint 应该不包含 path 信息吧

@Ocyss 你可以改成这样试试？

服务器地址: https://dav.jianguoyun.com
文件夹路径: /wfhg-cc

**Comment by sheepzh** [comment]
我自己试了下坚果云的 API，应该是 QPS 到上限了。文件夹里是有数据的。我看后面能不能加个 限制参数

**Comment by Ocyss** [comment]
> Gist API 的修复已发布至 Edge：v2.5.1
> 
> 欢迎更新 ^ ^

gist 能使用了, 谢谢作者
