### ISSUE TITLE
[BUG] Broken layout of calendar picker in Firefox 132

### ISSUE THREAD

**Issue by artpoli** [sheepzh/timer#326]
Version: v2.5.1
OS: Win
Browser: Firefox 132

After Firefox updated to the version 132 the calendar layout of time picker became broken.
Also, the checkboxes and some other UI elements look weird.
Everything looks good in Chromium, though...
Adding the screenshots below.

![зображення](https://github.com/user-attachments/assets/d8d3504c-6be8-4470-a4a8-1932fdcd7685)

![зображення](https://github.com/user-attachments/assets/5a5f6a87-f552-4c0e-93df-7c85ac685865)

**Comment by sheepzh** [comment]
I'll check it, thanks for your report!

**Comment by sheepzh** [comment]
I found the reason. Because Firefox changes the URL of the extension page. This extension cannot set the style flag for RTL languages.

I'll adapt to the new URL of Firefox. Thanks again!

**Comment by sheepzh** [comment]
@artpoli  v2.5.2 fixed, please upgrade
