### ISSUE TITLE
[BUG] 持续的高cpu占用

### ISSUE THREAD

**Issue by Ovler-Young** [sheepzh/timer#327]
## Tell me the environment / 请先填写版本信息

Version: 2.5.0
OS: Windows
Browser: Chrome-130.0.6723.92 

## Detail / Bug 详情

持续的高cpu占用

![image](https://github.com/user-attachments/assets/7c2e5320-4d75-4cc5-8efc-220b143ed7f8)

于最近2~3小时内出现，禁用插件后恢复，一开启插件就开吃cpu。具体原因未知。

**Comment by sheepzh** [comment]
@Ovler-Young 等我查明一下，麻烦先禁用一下。如果，您能够帮忙测试一下 Edge 最新版本在您的设备上是否有同样的问题就更好了

**Comment by sheepzh** [comment]
我也没复现成功，我先把 service worker 里的一些无效代码给清理一下吧
