### ISSUE TITLE
[FEATURE]弹窗页增加“打开时显示近7天”的选项

### ISSUE THREAD

**Issue by HexStan** [sheepzh/timer#328]
![屏幕截图 2024-11-04 213507](https://github.com/user-attachments/assets/26a07655-eddd-45ed-9b9b-c965633372ff)

**Comment by sheepzh** [comment]
@HexStan 已开发完毕，下个版本 (v2.5.3) 发布哈，改动量比较大。如果遇到没测全的 bug，欢迎及时反馈~

![image](https://github.com/user-attachments/assets/5b191861-55d4-4511-a9d6-701bca57122f)
