### ISSUE TITLE
💡💡💡 Force to install this extension for Firefox

### ISSUE THREAD

**Issue by curiousdreamer** [sheepzh/timer#331]
Tell me the environment

Version: 2.5.4
OS: Windows
Browser: Firefox

Detail

It would be nice if you could be able to force install this extension on Firefox on Windows, specifically because I mainly use this extension to limit the amount of time I spend on subreddits I currently joined on Reddit on the Time Limit tab. For some reason, I cannot force install this extension on Firefox in Windows, but I am able to do so on Chrome (retains these settings) and Edge (need Edge ver of extension which you provide and resets settings). I followed the [instructions here](https://www.proginosko.com/leechblock/faq/remove-extension-firefox/) for a very similar extension but it did not work in this case.

**Comment by sheepzh** [comment]
I've never thought about this, sounds interesting. I will find out how to implement this

**Comment by sheepzh** [comment]
@curiousdreamer Hello, as the article you mentioned says, you can add the same registry item to force install this extension for Firefox. Just only replace the data `leechblockng@proginosko.com` with `{a8cf72f7-09b7-4cd4-9aaa-7a023bf09916}`

**Comment by curiousdreamer** [comment]
Hello, I tried adding that registry key you mentioned and restarted my computer and browser, which did not work to permanently install this extension. I even tried uninstalling the extension, adding the registry key, and restarting my computer and browser, which did not work either. I am not sure if I am doing something wrong or if it's because there needs to be a "custom" string value as seen with the other extension I use.

**Comment by sheepzh** [comment]
@curiousdreamer Hello, sorry for replay late. 

Please check the path of your registry editor is `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Extensions\Locked`, and any item with value equalling to `{a8cf72f7-09b7-4cd4-9aaa-7a023bf09916}` was added under this key, like this following sceenshot shows

![image](https://github.com/user-attachments/assets/f5430099-9871-4b97-9035-67e839390915)

And this works on my Windows PC

![image](https://github.com/user-attachments/assets/9a28519b-f65a-4957-8f95-7e0fcf09c77f)

**Comment by curiousdreamer** [comment]
No worries, thank you for the help! I had assumed that the curly brackets were not needed when modifying the key value but in fact are needed to get the desired result.
