### ISSUE TITLE
[QUESTION] Why this plugin introduce clipboard permission?

### ISSUE THREAD

**Issue by Zxilly** [sheepzh/timer#38]
I noticed the latest version introduce a new permission requirement: clipboard. Can you please explain the reason for introducing this permission?
https://github.com/sheepzh/timer/blob/077cb9537800e3bca0015b9f8def122d0ae6b2ca/src/manifest.ts#L47

**Comment by sheepzh** [comment]
The clipboard reading permission is used to paste the special URL while setting time limit.

And this permission must be requested explicitly in manifest.json of the Firefox add-on, or some bugs will happen. While it does not need in chrome and edge.

You can see #35

**Comment by Zxilly** [comment]
@sheepzh Thanks.
