### ISSUE TITLE
“合并子域名”会略过三级/四级域名

### ISSUE THREAD

**Issue by YDX-2147483647** [sheepzh/timer#4]
“合并子域名”会把 sub.example.edu.cn 这种合并成 edu.cn，能不能改成 example.edu.cn 呢？

（标签页“我的数据”“报表明细”和小窗都有这个问题）

> 版本：v0.1.1，Edge (Chromium)。

辛苦了。

**Comment by sheepzh** [comment]
收到！

谢谢您的需求反馈！

**Comment by sheepzh** [comment]
@YDX-2147483647  该功能已经开发完成，新增域名合并规则设置，将随  v0.1.2 发布，预计 1-3 个工作日上架

功能预览：https://matirials-1256916044.cos.ap-guangzhou.myqcloud.com/merge-domain-rules.png

用户更新版本后，会默认插入三条合并规则。其中的一条能满足您的需求。

如果有后续需求，请留言我再重新开启这条 issue
