### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sc962** [sheepzh/timer#43]
## Tell me the enviroment / 请先填写版本信息

Version: [Extension version / 扩展版本] 0.3.6
OS: [操作系统:Mac/Linux/Win] WIN11 22000.282
Browser: [浏览器名称:Chrome/Edge/Firefox]-[浏览器版本，选填]FIREFOX 93.0

## Detail / Bug 详情

[Describe the bug / 描述您使用过程中遇到的问题] 安装几天了都没任何数据。

**Comment by sheepzh** [comment]
抱歉，由于在 Firefox 里使用这个插件的人数太少了，所以上次更新版本时没测 ff。
这个问题已经修复了，在扩展页面（about:addons）更新到 0.3.7 就 OK 了。

**Comment by sc962** [comment]
> 
> 
> 抱歉，由于在 Firefox 里使用这个插件的人数太少了，所以上次更新版本时没测 ff。 这个问题已经修复了，在扩展页面（about:addons）更新到 0.3.7 就 OK 了。

已经自动更新，使用正常了。非常感谢。

**Comment by sheepzh** [comment]
> 已经自动更新，使用正常了。非常感谢。

谢谢你的反馈，那我先 close 这个 issue 啦
