### ISSUE TITLE
[FEATURE]报表明细统计范围精确到分

### ISSUE THREAD

**Issue by Vant1032** [sheepzh/timer#45]
之所以提出这样的需求是因为我工作和回家后都会使用chrome，我希望统计的是我下班后的使用情况，上班的就不需要统计了。因此如果能够将报明细的统计范围筛选精确到分我就可以筛选我下班后的使用情况。

如果这种实现方式对你有问题，我希望能够新增一个功能：指定哪段时间不需要统计使用情况，当然这样可能就不够实用了，因为下班时间不一定在特定时间点。如果能够增加筛选精确到分的话，除了我这种需求能够满足，事实上用户对于任意时间段的使用情况的统计的需求都被满足了。

**Comment by sheepzh** [comment]
首先谢谢你的反馈，我大概明白你的需求。

但是由于数据是存储在浏览器提供的 5M 本地 storage  里，考虑到查询性能和内存空间，按天✖️网站的维度进行统计已经算是很小的计时粒度了。

所以为了满足您的需求，第二种开关的方案更加合适，不过至于是固定时间点还是实时手动开关可以再考虑。

如果您是需要区别工作和个人的上网时间的话，有一个方案可能更符合实际：把工作所需要浏览的网站全部加入白名单。

**Comment by Vant1032** [comment]
好的，谢谢你提供这么好的插件，代码写得很好看。
