### ISSUE TITLE
[FEATURE] 增加仪表盘，放置热力图等可视化报表

### ISSUE THREAD

**Issue by Ovler-Young** [sheepzh/timer#94]
希望能增加各个网站使用时间的热力图，类似于 Github 贡献热力图

**Comment by sheepzh** [comment]
如果增加一个 dashboard 面板页，放置各种可视化数据，似乎是更好的解决方案

**Comment by Ovler-Young** [comment]
这的确是一个更好的解决方案

**Comment by sheepzh** [comment]
功能变更：

- [ ] 新增菜单栏：仪表盘/Dashboard
- [ ] 用户打开后台页时不再默认打开上一次访问的页面，改为默认打开仪表盘
- [ ] 新增反馈问卷入口

仪表盘页面：
- [ ] 统计指标项
- [ ] 热力图
- [ ] 周环比玫瑰图
- [ ] top  k

**Comment by sheepzh** [comment]
新增功能导致原来的 EChart 图标不可用，待修复：

- [ ] 上网习惯
- [ ] 历史趋势

**Comment by sheepzh** [comment]
后续方向：
- [ ] 将目前的历史趋势功能升级为网站维度的使用情况分析
这样数据展示将会大致分为三个视角：
1. 仪表盘的全局分析数据
2. 报表明细的原始数据
3. 网站分析页的单网站分析数据
在此之后，数据展示会持续围绕这三个视角迭代优化
