### ISSUE TITLE
[BUG] 今日数据处点击“其他”会跳转到 http://xn--8mqu7d/

### ISSUE THREAD

**Issue by Ovler-Young** [sheepzh/timer#95]
## Tell me the enviroment / 请先填写版本信息
Version: 0.9.0
OS: Win
Browser: Chrome
## Detail / Bug 详情
今日数据处点击“其他”会跳转到 [其他/](http://xn--8mqu7d/) 是一个错误的的网址。
预期行为也许为，跳转到当日报表明细中未在今日数据处显示的地方，如，在今日数据处显示10条的情况下，点击其他应该跳转至今日数据报表明细中第二页。

**Comment by sheepzh** [comment]
之前并没有考虑点击其他的跳转反应，所以您反馈的这个 bug 更像是一个优化需求。不过确实很值得实现
