### ISSUE TITLE
[FEATURE] 默认使用“Public Suffix+1”合并子域名

### ISSUE THREAD

**Issue by tiansh** [sheepzh/timer#97]
合并子域名时默认使用“[Public Suffix](https://publicsuffix.org/)+1”。这样基本可以满足大多数用户的使用习惯，而且可以省去很多配置的麻烦。

Public Suffix: https://publicsuffix.org/

**Comment by sheepzh** [comment]
谢谢建议！！
看了很好 XXXXD （命中了我的知识盲区

**Comment by sheepzh** [comment]
已于  v0.9.3 发布
